RadioHead: RHNRFSPIDriver Class Reference
RHNRFSPIDriver Class Reference
Base class for a RadioHead driver that use the SPI bus to communicate with its transport hardware.
#include <RHNRFSPIDriver.h>
Public Member Functions
RHNRFSPIDriver (uint8_t slaveSelectPin=SS, RHGenericSPI &spi=hardware_spi)
bool init ()
uint8_t spiCommand (uint8_t command)
uint8_t spiRead (uint8_t reg)
uint8_t spiWrite (uint8_t reg, uint8_t val)
uint8_t spiBurstRead (uint8_t reg, uint8_t *dest, uint8_t len)
uint8_t spiBurstWrite (uint8_t reg, const uint8_t *src, uint8_t len)
Public Member Functions inherited from RHGenericDriver
RHGenericDriver ()
Constructor.
virtual bool available ()=0
virtual bool recv (uint8_t *buf, uint8_t *len)=0
virtual bool send (const uint8_t *data, uint8_t len)=0
virtual uint8_t maxMessageLength ()=0
virtual void waitAvailable ()
virtual bool waitPacketSent ()
virtual bool waitPacketSent (uint16_t timeout)
virtual bool waitAvailableTimeout (uint16_t timeout)
virtual void setThisAddress (uint8_t thisAddress)
virtual void setHeaderTo (uint8_t to)
virtual void setHeaderFrom (uint8_t from)
virtual void setHeaderId (uint8_t id)
virtual void setHeaderFlags (uint8_t set, uint8_t clear=RH_FLAGS_APPLICATION_SPECIFIC)
virtual void setPromiscuous (bool promiscuous)
virtual uint8_t headerTo ()
virtual uint8_t headerFrom ()
virtual uint8_t headerId ()
virtual uint8_t headerFlags ()
int8_t lastRssi ()
RHMode mode ()
void setMode (RHMode mode)
Sets the operating mode of the transport.
virtual bool sleep ()
uint16_t rxBad ()
uint16_t rxGood ()
uint16_t txGood ()
Protected Attributes
RHGenericSPI & _spi
Reference to the RHGenericSPI instance to use to trasnfer data with teh SPI device.
uint8_t _slaveSelectPin
The pin number of the Slave Selct pin that is used to select the desired device.
Protected Attributes inherited from RHGenericDriver
volatile RHMode _mode
The current transport operating mode.
uint8_t _thisAddress
This node id.
bool _promiscuous
Whether the transport is in promiscuous mode.
volatile uint8_t _rxHeaderTo
TO header in the last received mesasge.
volatile uint8_t _rxHeaderFrom
FROM header in the last received mesasge.
volatile uint8_t _rxHeaderId
ID header in the last received mesasge.
volatile uint8_t _rxHeaderFlags
FLAGS header in the last received mesasge.
uint8_t _txHeaderTo
TO header to send in all messages.
uint8_t _txHeaderFrom
FROM header to send in all messages.
uint8_t _txHeaderId
ID header to send in all messages.
uint8_t _txHeaderFlags
FLAGS header to send in all messages.
volatile int8_t _lastRssi
The value of the last received RSSI value, in some transport specific units.
volatile uint16_t _rxBad
Count of the number of bad messages (eg bad checksum etc) received.
volatile uint16_t _rxGood
Count of the number of successfully transmitted messaged.
volatile uint16_t _txGood
Count of the number of bad messages (correct checksum etc) received.
Additional Inherited Members
Public Types inherited from RHGenericDriver
enum RHMode {
RHModeInitialising = 0, RHModeSleep, RHModeIdle, RHModeTx,
RHModeRx
}
Defines different operating modes for the transport hardware.
Static Public Member Functions inherited from RHGenericDriver
static void printBuffer (const char *prompt, const uint8_t *buf, uint8_t len)
Detailed Description
Base class for a RadioHead driver that use the SPI bus to communicate with its transport hardware.
This class can be subclassed by Drivers that require to use the SPI bus. It can be configured to use either the RHHardwareSPI class (if there is one available on the platform) of the bitbanged RHSoftwareSPI class. The dfault behaviour is to use a pre-instantiated built-in RHHardwareSPI interface.
SPI bus access is protected by ATOMIC_BLOCK_START and ATOMIC_BLOCK_END, which will ensure interrupts are disabled during access.
The read and write routines use SPI conventions as used by Nordic NRF radios and otehr devices, but these can be overriden in subclasses if necessary.
Application developers are not expected to instantiate this class directly: it is for the use of Driver developers.
Constructor & Destructor Documentation
RHNRFSPIDriver::RHNRFSPIDriver (uint8_t slaveSelectPin = SS, RHGenericSPI & spi = hardware_spi)
Constructor
Parameters
[in] slaveSelectPin The controller pin to use to select the desired SPI device. This pin will be driven LOW during SPI communications with the SPI device that uis iused by this Driver.
[in] spi Reference to the SPI interface to use. The default is to use a default built-in Hardware interface.
Member Function Documentation
bool RHNRFSPIDriver::init () virtual
Initialise the Driver transport hardware and software. Make sure the Driver is properly configured before calling init().
Returns
true if initialisation succeeded.
Reimplemented from RHGenericDriver.
References _slaveSelectPin, _spi, and RHGenericSPI::begin().
Referenced by RH_NRF905::init(), and RH_NRF24::init().
uint8_t RHNRFSPIDriver::spiBurstRead (uint8_t reg, uint8_t * dest, uint8_t len)
Reads a number of consecutive registers from the SPI device using burst read mode
Parameters
[in] reg Register number of the first register
[in] dest Array to write the register values to. Must be at least len bytes
[in] len Number of bytes to read
Returns
Some devices return a status byte during the first data transfer. This byte is returned. it may or may not be meaningfule depending on the the type of device being accessed.
References _slaveSelectPin, _spi, and RHGenericSPI::transfer().
Referenced by RH_NRF905::available(), RH_NRF24::available(), RH_NRF905::spiBurstReadRegister(), and RH_NRF24::spiBurstReadRegister().
uint8_t RHNRFSPIDriver::spiBurstWrite (uint8_t reg, const uint8_t * src, uint8_t len)
Write a number of consecutive registers using burst write mode
Parameters
[in] reg Register number of the first register
[in] src Array of new register values to write. Must be at least len bytes
[in] len Number of bytes to write
Returns
Some devices return a status byte during the first data transfer. This byte is returned. it may or may not be meaningfule depending on the the type of device being accessed.
References _slaveSelectPin, _spi, and RHGenericSPI::transfer().
Referenced by RH_NRF905::send(), RH_NRF24::send(), RH_NRF905::setNetworkAddress(), RH_NRF905::spiBurstWriteRegister(), and RH_NRF24::spiBurstWriteRegister().
uint8_t RHNRFSPIDriver::spiCommand (uint8_t command)
Sends a single command to the device
Parameters
[in] command The command code to send to the device.
Returns
Some devices return a status byte during the first data transfer. This byte is returned. it may or may not be meaningfule depending on the the type of device being accessed.
References _slaveSelectPin, _spi, and RHGenericSPI::transfer().
Referenced by RH_NRF24::flushRx(), RH_NRF24::flushTx(), RH_NRF905::statusRead(), and RH_NRF24::statusRead().
uint8_t RHNRFSPIDriver::spiRead (uint8_t reg)
Reads a single register from the SPI device
Parameters
[in] reg Register number
Returns
The value of the register
References _slaveSelectPin, _spi, and RHGenericSPI::transfer().
Referenced by RH_NRF24::available(), RH_NRF905::spiReadRegister(), and RH_NRF24::spiReadRegister().
uint8_t RHNRFSPIDriver::spiWrite (uint8_t reg, uint8_t val)
Writes a single byte to the SPI device
Parameters
[in] reg Register number
[in] val The value to write
Returns
Some devices return a status byte during the first data transfer. This byte is returned. it may or may not be meaningfule depending on the the type of device being accessed.
References _slaveSelectPin, _spi, and RHGenericSPI::transfer().
Referenced by RH_NRF24::init(), RH_NRF905::spiWriteRegister(), and RH_NRF24::spiWriteRegister().
The documentation for this class was generated from the following files:
RHNRFSPIDriver.h
RHNRFSPIDriver.cpp